# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/tcl/1-clock.xdc

# XDC: imports/tcl/2-pins.xdc

# XDC: imports/tcl/3-bitstream.xdc

# Block Designs: bd/nexys_shell/nexys_shell.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nexys_shell || ORIG_REF_NAME==nexys_shell} -quiet] -quiet

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/nexys_shell_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nexys_shell_smartconnect_0_0 || ORIG_REF_NAME==nexys_shell_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/bd_4cab.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_0/bd_4cab_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_1/bd_4cab_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_2/bd_4cab_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_4/bd_4cab_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_5/bd_4cab_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_6/bd_4cab_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_7/bd_4cab_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_8/bd_4cab_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_9/bd_4cab_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_10/bd_4cab_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_11/bd_4cab_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_12/bd_4cab_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_13/bd_4cab_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_14/bd_4cab_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0_1/nexys_shell_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nexys_shell_proc_sys_reset_0_0 || ORIG_REF_NAME==nexys_shell_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/nexys_shell/ip/nexys_shell_mig_7series_0_0_1/nexys_shell_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nexys_shell_mig_7series_0_0 || ORIG_REF_NAME==nexys_shell_mig_7series_0_0} -quiet] -quiet

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_1/bd_4cab_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_1/bd_4cab_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_2/bd_4cab_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_2/bd_4cab_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_7/bd_4cab_s00a2s_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_8/bd_4cab_sarn_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_9/bd_4cab_srn_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_10/bd_4cab_sawn_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_11/bd_4cab_swn_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_12/bd_4cab_sbn_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_13/bd_4cab_m00s2a_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0_1/nexys_shell_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==nexys_shell_proc_sys_reset_0_0 || ORIG_REF_NAME==nexys_shell_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0_1/nexys_shell_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==nexys_shell_proc_sys_reset_0_0 || ORIG_REF_NAME==nexys_shell_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/nexys_shell/ip/nexys_shell_mig_7series_0_0_1/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0_ooc.xdc

# XDC: bd/nexys_shell/ip/nexys_shell_mig_7series_0_0_1/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nexys_shell_mig_7series_0_0 || ORIG_REF_NAME==nexys_shell_mig_7series_0_0} -quiet] -quiet

# XDC: bd/nexys_shell/nexys_shell_ooc.xdc
