# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.cache/wt [current_project]
set_property parent.project_path /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/mtahir/Xilinx/Vivado/2019.1/data/boards/board_files/nexys-a7-100t} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/pcore_config_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/a_ext_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/mmu_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/cache_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/pcore_interface_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/pcore_csr_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/ddr_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/plic_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/m_ext_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/spi_defs.svh
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/uart_defs.svh
}
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/pcore_config_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/a_ext_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/mmu_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/cache_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/pcore_interface_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/pcore_csr_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/ddr_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/plic_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/m_ext_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/spi_defs.svh]
set_property file_type "Verilog Header" [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/defines/uart_defs.svh]
read_verilog -library xil_defaultlib -sv {
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/amo.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/bmem.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/bmem_interface.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/clint/clint.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/core_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/csr.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/interconnect/dbus_interconnect.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/wb_dcache/dcache_data_ram.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/wb_dcache/dcache_tag_ram.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/decode.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/divider.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/mmu/dtlb.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/execute.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/fetch.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/forward_stall.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/icache/icache_data_ram.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/icache/icache_tag_ram.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/icache/icache_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/mmu/itlb.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/lsu.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/mem_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/mmu/mmu.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/muldiv.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/pipeline_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/plic/plic_gateway.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/plic/plic_regs.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/plic/plic_target.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/plic/plic_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/mmu/ptw.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/reg_file.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/soc_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/spi/spi_controller.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/spi/spi_datapath.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/spi/spi_fifo.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/spi/spi_regs.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/spi/spi_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/uart/uart.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/uart/uart_rx.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/peripherals/uart/uart_tx.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/UETRV-PCore/wb2axi.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/wb_dcache/wb_dcache_controller.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/wb_dcache/wb_dcache_datapath.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/memory/wb_dcache/wb_dcache_top.sv
  /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/rtl/core/pipeline/writeback.sv
}
read_verilog -library xil_defaultlib /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/imports/UETRV-PCore/top.v
add_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/nexys_shell.bd
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_1/bd_4cab_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_1/bd_4cab_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_2/bd_4cab_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_2/bd_4cab_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_7/bd_4cab_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_8/bd_4cab_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_9/bd_4cab_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_10/bd_4cab_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_11/bd_4cab_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_12/bd_4cab_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0_1/bd_0/ip/ip_13/bd_4cab_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0_1/nexys_shell_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0_1/nexys_shell_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0_1/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0_1/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/sources_1/bd/nexys_shell/nexys_shell_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/constrs_1/imports/tcl/1-clock.xdc
set_property used_in_implementation false [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/constrs_1/imports/tcl/1-clock.xdc]

read_xdc /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/constrs_1/imports/tcl/2-pins.xdc
set_property used_in_implementation false [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/constrs_1/imports/tcl/2-pins.xdc]

read_xdc /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/constrs_1/imports/tcl/3-bitstream.xdc
set_property used_in_implementation false [get_files /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/constrs_1/imports/tcl/3-bitstream.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/mtahir/SOC/FPGA/UETRV_PCore_FPGA_working3/PCore_FPGA/PCore_FPGA.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef -incremental_synth top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
