# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/1-clock.xdc

# XDC: /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/2-pins.xdc

# XDC: /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/3-bitstream.xdc

# Block Designs: /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/nexys_shell.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell || ORIG_REF_NAME==nexys_shell} -quiet] -quiet

# IP: /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/ip/nexys_shell_axi_bram_ctrl_0_0/nexys_shell_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell_axi_bram_ctrl_0_0 || ORIG_REF_NAME==nexys_shell_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/ip/nexys_shell_blk_mem_gen_0_0/nexys_shell_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell_blk_mem_gen_0_0 || ORIG_REF_NAME==nexys_shell_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/nexys_shell_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell_smartconnect_0_0 || ORIG_REF_NAME==nexys_shell_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/bd_4cab.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_0/bd_4cab_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_1/bd_4cab_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_2/bd_4cab_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_4/bd_4cab_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_5/bd_4cab_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_6/bd_4cab_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_7/bd_4cab_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_8/bd_4cab_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_9/bd_4cab_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_10/bd_4cab_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_11/bd_4cab_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_12/bd_4cab_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_13/bd_4cab_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_14/bd_4cab_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_15/bd_4cab_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_16/bd_4cab_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_17/bd_4cab_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_18/bd_4cab_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_19/bd_4cab_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_20/bd_4cab_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_21/bd_4cab_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_22/bd_4cab_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_23/bd_4cab_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_24/bd_4cab_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_25/bd_4cab_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_26/bd_4cab_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_27/bd_4cab_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_28/bd_4cab_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_29/bd_4cab_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_30/bd_4cab_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_31/bd_4cab_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0/nexys_shell_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell_mig_7series_0_0 || ORIG_REF_NAME==nexys_shell_mig_7series_0_0} -quiet] -quiet

# IP: /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0/nexys_shell_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell_proc_sys_reset_0_0 || ORIG_REF_NAME==nexys_shell_proc_sys_reset_0_0} -quiet] -quiet

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_blk_mem_gen_0_0/nexys_shell_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_1/bd_4cab_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_1/bd_4cab_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_2/bd_4cab_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_2/bd_4cab_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_4/bd_4cab_arsw_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_5/bd_4cab_rsw_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_6/bd_4cab_awsw_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_7/bd_4cab_wsw_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_8/bd_4cab_bsw_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_12/bd_4cab_s00a2s_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_13/bd_4cab_sarn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_14/bd_4cab_srn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_15/bd_4cab_sawn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_16/bd_4cab_swn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_17/bd_4cab_sbn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_18/bd_4cab_m00s2a_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_19/bd_4cab_m00arn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_20/bd_4cab_m00rn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_21/bd_4cab_m00awn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_22/bd_4cab_m00wn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_23/bd_4cab_m00bn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_25/bd_4cab_m01s2a_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_26/bd_4cab_m01arn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_27/bd_4cab_m01rn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_28/bd_4cab_m01awn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_29/bd_4cab_m01wn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_30/bd_4cab_m01bn_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nexys_shell_mig_7series_0_0 || ORIG_REF_NAME==nexys_shell_mig_7series_0_0} -quiet] -quiet

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0_ooc.xdc

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0/nexys_shell_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nexys_shell_proc_sys_reset_0_0 || ORIG_REF_NAME==nexys_shell_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0/nexys_shell_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nexys_shell_proc_sys_reset_0_0 || ORIG_REF_NAME==nexys_shell_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/nexys_shell_ooc.xdc
