# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/fpga-nexys-a7.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/fpga-nexys-a7.cache/wt [current_project]
set_property parent.project_path /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/fpga-nexys-a7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/fpga-nexys-a7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/pcore_config_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/a_ext_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/mmu_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/cache_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/pcore_interface_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/pcore_csr_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/ddr_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/plic_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/m_ext_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/spi_defs.svh
  /home/uetlhr/Documents/UETRV-PCore/rtl/defines/uart_defs.svh
}
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/pcore_config_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/a_ext_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/mmu_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/cache_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/pcore_interface_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/pcore_csr_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/ddr_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/plic_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/m_ext_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/spi_defs.svh]
set_property file_type "Verilog Header" [get_files /home/uetlhr/Documents/UETRV-PCore/rtl/defines/uart_defs.svh]
read_verilog -library xil_defaultlib -sv {
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/amo.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/bmem.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/bmem_interface.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/clint/clint.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/core_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/csr.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/interconnect/dbus_interconnect.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/decode.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/divider.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/mmu/dtlb.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/execute.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/fetch.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/forward_stall.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/icache/icache_controller.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/icache/icache_datapath.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/icache/icache_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/mmu/itlb.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/lsu.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/mem_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/mmu/mmu.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/muldiv.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/pipeline_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/plic/plic_gateway.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/plic/plic_regs.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/plic/plic_target.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/plic/plic_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/mmu/ptw.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/reg_file.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/soc_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/spi/spi_controller.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/spi/spi_datapath.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/spi/spi_fifo.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/spi/spi_regs.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/spi/spi_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/uart/uart.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/uart_ns/uart_ns.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/uart_ns/uart_ns_rx.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/uart_ns/uart_ns_tx.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/uart/uart_rx.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/peripherals/uart/uart_tx.sv
  /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/srcs/wb2axi.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/wb_dcache/wb_dcache_controller.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/wb_dcache/wb_dcache_datapath.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/memory/wb_dcache/wb_dcache_top.sv
  /home/uetlhr/Documents/UETRV-PCore/rtl/core/pipeline/writeback.sv
  /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/srcs/top.sv
}
add_files /home/uetlhr/Documents/UETRV-PCore/bd/nexys_shell/nexys_shell.bd
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_blk_mem_gen_0_0/nexys_shell_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_1/bd_4cab_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_1/bd_4cab_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_2/bd_4cab_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_2/bd_4cab_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_3/bd_4cab_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_4/bd_4cab_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_5/bd_4cab_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_6/bd_4cab_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_7/bd_4cab_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_8/bd_4cab_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_12/bd_4cab_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_13/bd_4cab_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_14/bd_4cab_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_15/bd_4cab_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_16/bd_4cab_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_17/bd_4cab_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_18/bd_4cab_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_19/bd_4cab_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_20/bd_4cab_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_21/bd_4cab_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_22/bd_4cab_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_23/bd_4cab_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_25/bd_4cab_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_26/bd_4cab_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_27/bd_4cab_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_28/bd_4cab_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_29/bd_4cab_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/bd_0/ip/ip_30/bd_4cab_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_mig_7series_0_0/nexys_shell_mig_7series_0_0/user_design/constraints/nexys_shell_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0/nexys_shell_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/ip/nexys_shell_proc_sys_reset_0_0/nexys_shell_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/uetlhr/AXI_new.gen/sources_1/bd/nexys_shell/nexys_shell_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/1-clock.xdc
set_property used_in_implementation false [get_files /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/1-clock.xdc]

read_xdc /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/2-pins.xdc
set_property used_in_implementation false [get_files /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/2-pins.xdc]

read_xdc /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/3-bitstream.xdc
set_property used_in_implementation false [get_files /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/constrs/3-bitstream.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/uetlhr/Documents/UETRV-PCore/fpga-nexys-a7/fpga-nexys-a7.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
