name: Pcore-riscof

on:
  push:
    branches:
      - '**'   # Trigger on all branches (including those from forks)
  pull_request:
    branches:
      - main   # Trigger on PRs targeting the main branch

jobs:

  pcore-verification:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3
      with:
        path: pcore

    - name: Install verilator and riscof
      run: |
       sudo apt-get update
       sudo apt-get install -y python3 python3-pip python3-venv
       pip3 install --upgrade pip
       sudo apt-get install -y gcc git autoconf automake libtool curl make unzip
       sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev
       sudo apt-get install verilator device-tree-compiler
       pip3 install git+https://github.com/riscv/riscof.git


    - name: Setup toolchain
      run: |
        wget -c https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.04.29/riscv64-elf-ubuntu-20.04-nightly-2023.04.29-nightly.tar.gz
        tar -xzf riscv64-elf-ubuntu-20.04-nightly-2023.04.29-nightly.tar.gz
        echo $GITHUB_WORKSPACE/riscv/bin >> $GITHUB_PATH

    - name: Update Submodule to clone arch-tests
      run: |
        cd pcore/verif
        git submodule update --init

    - name: Setup SAIL-RISCV Model
      run: |
        tar -xzf pcore/verif/bin/sail-riscv.tar.gz
        echo $GITHUB_WORKSPACE/sail-riscv >> $GITHUB_PATH

    - name: Install riscv-isac
      run: |
        cd pcore/verif/bin/riscv-isac
        pip3 install --editable .

    - name: Run Verification Framework
      run: |
        cd pcore/verif
        chmod +x run-tests.sh
        ./run-tests.sh
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Test_report
        path: |
          pcore/verif/riscof_work/report.html
          pcore/verif/riscof_work/style.css
